services:
  backend-counter:
    build: ./backend # Path to your Flask app's Dockerfile
    volumes:
      - ./backend:/server
    depends_on:
      - database-counter # Ensures db service is started before flask_api

  frontend-counter:
    build: ./frontend # Path to your React app's Dockerfile
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend-counter # Optional: Ensures flask_api service is started before react_frontend

  database-counter:
    build: ./database # Adjust this path to where your MySQL Dockerfile is located
    ports:
      - "8082:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
