services:
  backend-counter:
    image: backend-counter-dev-i
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-counter-dev-c
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/server
    environment:
      - FLASK_ENV=development
    depends_on:
      - database-counter

  frontend-counter:
    image: frontend-counter-dev-i
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-counter-dev-c
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - backend-counter

  database-counter:
    image: database-counter-dev-i
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database-counter-dev-c
    ports:
      - "8082:3306"
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./secrets/dev:/run/secrets:ro
    secrets:
      - db_root_password
      - db_password

secrets:
  db_root_password:
    file: ./secrets/dev/db_root_password
  db_password:
    file: ./secrets/dev/db_password

volumes:
  mysql_data:
    name: mysql-counter-dev-v
