CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL CHECK (name <> ''),
    hashpassword CHAR(64) NOT NULL,
    salt BINARY(32) NOT NULL,
    token CHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE users AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS usercount (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL CHECK (name <> ''),
    count INTEGER NOT NULL DEFAULT 0
);


ALTER TABLE users AUTO_INCREMENT = 1;
